[tool.poetry]
name = "rfind-web"
version = "0.1.0"
description = ""
authors = ["Nicholas Bruce <nsbruce@uvic.ca>"]
readme = "README.md"
packages = [{include = "rfind_web"}]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.4"
python-socketio = "^5.6.0"
websocket-client = "^1.3.2"
requests = "^2.27.1"


[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
black = "^22.3.0"
mypy = "^0.960"
pytest = "^7.1.2"
poethepoet = "^0.13.1"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
generate-env = 'rfind_web.environment.generate:main'
sim = 'rfind_web.providers.sim:start'
usrp = 'rfind_web.providers.usrp:start'
# s3 = 'rfind_web.providers.s3:start'
# h5 = 'rfind_web.providers.h5:start'

[tool.black]
target-version = ["py39"]
preview="True"

[tool.isort]
profile="black"

[tool.mypy]
python_version = 3.9
plugins = ["numpy.typing.mypy_plugin"]

[tool.pytest.ini_options]
testpaths = "tests"

[tool.flake8]
ignore = ['E203']
max-line-length = 88

[tool.poe.tasks]

    [tool.poe.tasks.test]
    cmd = "pytest"
    help = 'Run tests'

    [tool.poe.tasks.sort]
    cmd = "isort ."
    help = "Run isort (sort imports alphabetically)"

    [tool.poe.tasks.blacken]
    cmd = "black ."
    help = "Run black (format code)"

    [tool.poe.tasks.mypyify]
    cmd = "mypy ."
    help = "Run mypy (type check)"

    [tool.poe.tasks.flake8ify]
    cmd = "flake8 ."
    help = "Run flake8 (lint code)"

    [tool.poe.tasks.format]
    sequence = ["sort", "blacken"]
    help = "Run isort and black (format code)"

    [tool.poe.tasks.lint]
    sequence = ["mypyify", "flake8ify"]
    help = "Run mypy and flake8 (lint code)"