from .defaults import (
    DEFAULT_DATA_VARS,
    DEFAULT_S3_VARS,
    DEFAULT_SIM_VARS,
    DEFAULT_SOCKETIO_VARS,
)
from .utils import get_env_dir


def main():

    env_dir = get_env_dir()

    # create file to write to
    with open(env_dir / ".env", "w") as f:

        # Set a header
        f.write("# This file is autogenerated via `python rfind_web.environment.generate`")
        f.write("# To override these values, copy this file to .env.local")
        f.write("# and make your overrides there")
        f.write("\n")

        f.write("# SOCKETIO")
        for key, val in DEFAULT_SOCKETIO_VARS.items():
            f.write("{}={}\n".format(key, val))
        f.write("\n")

        f.write("# S3")
        for key, val in DEFAULT_S3_VARS.items():
            f.write("{}={}\n".format(key, val))
        f.write("\n")

        f.write("# DATA")
        for key, val in DEFAULT_DATA_VARS.items():
            f.write("{}={}\n".format(key, val))
        f.write("\n")


if __name__ == "__main__":
    main()
